// utils/frasesMotivadoras.js

const frases = [
    // --- ESPARTANAS Y GUERRERAS ---
    "No te detengas cuando estés cansado, detente cuando hayas terminado.",
    "Suda más en el entrenamiento y sangrarás menos en la batalla.",
    "Tu cuerpo puede aguantar casi cualquier cosa. Es a tu mente a la que tienes que convencer.",
    "El miedo es una reacción. El coraje es una decisión.",
    "Si fuera fácil, todo el mundo lo haría.",
    "Conviértete en la persona que nadie creyó que podrías ser.",
    "La disciplina es hacer lo que odias hacer, pero hacerlo como si lo amaras.",

    // --- DISCIPLINA Y CONSTANCIA ---
    "La motivación te hace empezar, el hábito te mantiene.",
    "No cuentes los días, haz que los días cuenten.",
    "Hoy haré lo que otros no hacen, para mañana conseguir lo que otros no pueden.",
    "El único mal entrenamiento es el que no ha ocurrido.",
    "Tu 'yo' del futuro te agradecerá el esfuerzo de hoy.",
    "La excelencia no es un acto, es un hábito.",
    "Excusas o resultados. Tú eliges.",
    "Un viaje de mil millas comienza con un solo paso.",
    "No esperes a tener ganas. Entrena sin ganas y las ganas aparecerán.",
    "La consistencia es la clave del éxito.",

    // --- FUERZA Y SUPERACIÓN ---
    "Cae siete veces, levántate ocho.",
    "Lo que no te mata te hace más fuerte.",
    "Sé más fuerte que tu mejor excusa.",
    "El dolor de hoy es la fuerza de mañana.",
    "No busques tiempo, créalo.",
    "Tu cuerpo escucha todo lo que dice tu mente. Sé positivo.",
    "Supera tus límites, no te conformes con ellos.",
    "El sudor es la grasa llorando.",
    "Entrena como una bestia para lucir como un dios.",
    "No pares hasta que te sientas orgulloso.",

    // --- ESTOICISMO Y MENTALIDAD ---
    "El obstáculo es el camino.",
    "No podemos elegir lo que nos pasa, pero sí cómo respondemos.",
    "Domina tu mente o ella te dominará a ti.",
    "La suerte es lo que ocurre cuando la preparación coincide con la oportunidad.",
    "No es lo que tienes, es lo que haces con lo que tienes.",
    "La verdadera fuerza está en el control de uno mismo.",
    "Céntrate en lo que puedes controlar.",
    "La incomodidad es el precio del crecimiento.",
    "Hazlo o no lo hagas, pero no lo intentes.",
    "La paz viene de saber que hiciste todo lo posible.",

    // --- DIETA Y SALUD ---
    "Eres lo que comes, así que no seas barato, fácil o falso.",
    "Tu cuerpo es tu templo. Cuídalo.",
    "La comida es combustible, no terapia.",
    "Comer bien es una forma de respetarte a ti mismo.",
    "No arruines un buen entrenamiento con una mala dieta.",
    "Invierte en tu salud, es la mejor cuenta de ahorros.",
    "Cada comida es una oportunidad para nutrir tu cuerpo.",
    "El agua es vida. ¡Hidrátate!",
    "Desayuna como un rey, almuerza como un príncipe y cena como un mendigo.",
    "Tu salud es tu verdadera riqueza.",

    // --- CORTAS Y DIRECTAS ---
    "¡Vamos! 💪",
    "Sin dolor no hay ganancia.",
    "Hazlo ahora.",
    "Cierra la boca y entrena.",
    "Menos charla, más acción.",
    "Enfócate.",
    "Tú puedes.",
    "No te rindas.",
    "Sigue adelante.",
    "Rompe tus límites.",

    // --- GENERADOR DE RELLENO (Frases extra para variedad) ---
    "Recuerda por qué empezaste.",
    "La única competición es contigo mismo.",
    "Pequeños progresos suman grandes resultados.",
    "Un día o día uno. Tú decides.",
    "No desees que fuera más fácil, desea ser mejor.",
    "El éxito no se da, se gana.",
    "Sé la mejor versión de ti mismo.",
    "El momento es ahora.",
    "Transforma tus sueños en metas.",
    "Cree en ti mismo y serás imparable.",
    "La actitud lo es todo.",
    "Entrena duro, vive feliz.",
    "Tu potencial es infinito.",
    "Nada cambia si nada cambia.",
    "Sé valiente, sé fuerte.",
    "El éxito ama la preparación.",
    "Desafíate a ti mismo cada día.",
    "Vive sin arrepentimientos.",
    "Haz que suceda.",
    "La pereza es el enemigo.",
    "Gana la mañana, gana el día.",
    "No te compares, compite contigo.",
    "El esfuerzo total es la victoria total.",
    "Mantén la vista en la meta.",
    "La fuerza de voluntad es un músculo.",
    "No hay atajos para ningún lugar que valga la pena.",
    "Sé tu propio héroe.",
    "Disfruta del proceso.",
    "Cada repetición cuenta.",
    "Respira, enfócate, ejecuta.",
    "La disciplina es libertad.",
    "Nunca es tarde para cambiar.",
    "Sé implacable.",
    "Construye tu legado.",
    "Vive con pasión.",
    "Entrena para la vida.",
    "Sé un guerrero, no un preocupado.",
    "La acción cura el miedo.",
    "Hazlo por ti.",
    "Brilla con luz propia."
    // Puedes seguir añadiendo frases aquí...
];

module.exports = frases;